### ISSUE TITLE
Help to progress?

### ISSUE THREAD

**Issue by echarles** [matrix-org/collaborative-documents#2]
@jryans Using Prosemirror to connect to a Matrix server sounds like something very interesting.

Can I do anything to progress on this?

**Comment by jryans** [comment]
Thanks for the interest, I agree it's exciting! 😄 

I think I first need to sort out my own thoughts and bit better, and then I imagine there'll be clearly paths to help from there. I suggest watching out for news in #beyond-chat:matrix.org.
